# Generated by Django 3.1.4 on 2020-12-28 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0004_auto_20201228_0939'),
        ('problem', '0007_delete_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to='submissions/')),
                ('source_code', models.TextField(blank=True, null=True)),
                ('submit_time', models.DateTimeField()),
                ('language', models.CharField(max_length=100)),
                ('verdict', models.CharField(max_length=100)),
                ('time', models.IntegerField(default=1000)),
                ('memory', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission',
                'ordering': ['-submit_time'],
            },
        ),
    ]
