# Generated by Django 3.1.4 on 2021-01-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0007_auto_20210112_1432'),
        ('submission', '0002_remove_submission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='username',
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
