# Generated by Django 3.1.4 on 2021-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20210112_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
