# Generated by Django 3.1.4 on 2021-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20210127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source_code',
            field=models.TextField(),
        ),
    ]
