# Generated by Django 3.1.4 on 2021-01-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20210127_1724'),
        ('submission', '0006_auto_20210127_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.problem'),
        ),
    ]
