# Generated by Django 3.1.4 on 2020-12-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('ICPC', 'ICPC'), ('IOI', 'IOI')], max_length=100)),
                ('phase', models.CharField(choices=[('future', 'future'), ('past', 'past'), ('ongoing', 'ongoing')], default='future', max_length=100)),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('novice', 'novice'), ('standard', 'standard'), ('general', 'general'), ('major', 'major')], default='novice', max_length=100)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='ContestRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('rating_change', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
            options={
                'db_table': 'contest_rating',
                'ordering': ['point', '-penalty'],
            },
        ),
    ]
