# Generated by Django 3.1.4 on 2020-12-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20201222_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='phase',
        ),
    ]
