# Generated by Django 3.1.4 on 2020-12-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_remove_contest_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='style',
            new_name='rule',
        ),
    ]
