# Generated by Django 3.1.4 on 2021-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20210112_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
