# Generated by Django 3.1.4 on 2021-01-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20210127_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestrating',
            name='verdicts',
            field=models.JSONField(default={'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0, 'F': 0, 'G': 0, 'H': 0, 'I': 0, 'J': 0, 'K': 0, 'L': 0, 'M': 0, 'N': 0}),
        ),
        migrations.AlterField(
            model_name='contestrating',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contest.contest'),
        ),
    ]
