# Generated by Django 3.1.4 on 2021-01-27 16:23

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_contestrating_penalties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestrating',
            name='penalties',
            field=models.JSONField(default=contest.models.initial_verdicts),
        ),
        migrations.AlterField(
            model_name='contestrating',
            name='verdicts',
            field=models.JSONField(default=contest.models.initial_verdicts),
        ),
    ]
