# Generated by Django 3.1.4 on 2021-01-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20210127_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestrating',
            options={'ordering': ['point', 'penalty']},
        ),
    ]
