# Generated by Django 3.1.4 on 2021-01-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20210127_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestrating',
            options={'ordering': ['-solved_count', 'penalty']},
        ),
    ]
