# Generated by Django 3.1.4 on 2021-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20210127_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestrating',
            name='computed',
            field=models.BooleanField(default=False),
        ),
    ]
