# Generated by Django 3.1.4 on 2020-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20201222_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to='submissions/'),
        ),
    ]
