# Generated by Django 3.1.4 on 2020-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20201226_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Judging', max_length=100),
        ),
    ]
