# Generated by Django 3.1.4 on 2020-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20201226_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input_format',
            new_name='input_description',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='output_format',
            new_name='output_description',
        ),
        migrations.AddField(
            model_name='problem',
            name='samples',
            field=models.JSONField(default={}),
        ),
    ]
