# Generated by Django 3.1.4 on 2020-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20201227_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=models.JSONField(default=dict),
        ),
    ]
