# Generated by Django 3.1.4 on 2020-12-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20201227_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
