# Generated by Django 3.1.4 on 2021-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20210104_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='clarification',
            field=models.TextField(null=True),
        ),
    ]
