# Generated by Django 3.1.4 on 2021-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='en',
            field=models.TextField(default='No editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='kg',
            field=models.TextField(default='No editorial'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='ru',
            field=models.TextField(null='No editorial'),
        ),
    ]
