# Generated by Django 3.1.4 on 2021-02-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_auto_20210220_0604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editorial',
            table='editorial',
        ),
    ]
